apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-status-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-status-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-status-role-binding
subjects:
- kind: ServiceAccount
  name: deployment-status-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployment-status-role
  apiGroup: rbac.authorization.k8s.io 